### ISSUE TITLE
Give up and remove strict .noSideEffect requirement?

### ISSUE THREAD

**Issue by planetis-m** [status-im/nim-drchaos#15]
Reading from a string stream shouldn't imply side effects right? But Nim's std/streams don't distinguish string from a file stream.

**Comment by arnetheduck** [comment]
whenever dynamic dispatch of any kind is used, one has to plan for the _most_ permissive option in the API - if you want to be able to use both strings and files as a _consumer_ of streams, you have to be prepared for side effects even if a particular concrete implementation doesn't exhibit them (the same goes for exception tracking)

**Comment by planetis-m** [comment]
Makes total sense, however fuzz targets shouldn't have side effects, so what to do, remove? I will remove it and document instead you should use funcs as targets whenever you can.

**Comment by planetis-m** [comment]
Nah not 100% correct, let's relax this rule.
